fix error related with change in signature of Atom
The error was:
in opencog.atomspace.Atom.__cinit__ ....
TypeError: __cinit__() takes exactly 2 positional arguments (1 given)